from xml.dom import minidom

root = minidom.Document()
lista_persoane = root.createElement("Lista_Persoane")
root.appendChild(lista_persoane)

p = root.createElement("Persoana")
p.setAttribute("IdPersoana", "1820521350068")
nume = root.createElement("Nume")
nume.setAttribute("Length","1")
nodTextNume = root.createTextNode("Aritoni")
nume.appendChild(nodTextNume)
prenume = root.createElement("Prenume")
prenume.setAttribute("Lehgth","2");
nodTextPrenume = root.createTextNode("Ovidiu Constantin")
prenume.appendChild(nodTextPrenume)
sex= root.createElement("Sex")
nodTextSex = root.createTextNode("Masculin")
sex.appendChild(nodTextSex)
cnp = root.createElement("CNP")
nodTextCNP = root.createTextNode("1820521350068")
cnp.appendChild(nodTextCNP)
dataNasterii = root.createElement("DataNasterii")
data = root.createElement("Data")
dataNasterii.appendChild(data)
an = root.createElement("An")
nodTextAn = root.createTextNode("1982")
an.appendChild(nodTextAn)
data.appendChild(an)
luna = root.createElement("Luna")
month = root.createElement("month")
month.setAttribute("nr", "3")
month.setAttribute("ro", "mai")
month.setAttribute("en", "may")
luna.appendChild(month)
data.appendChild(luna)
zi = root.createElement("Zi")
nodTextZi = root.createTextNode("21")
zi.appendChild(nodTextZi)
data.appendChild(zi)

lista_persoane.appendChild(p)
lista_persoane.appendChild(nume)
lista_persoane.appendChild(prenume)
lista_persoane.appendChild(sex)
lista_persoane.appendChild(cnp)
lista_persoane.appendChild(dataNasterii)

xml_string = root.toprettyxml(indent="\t")
file = "persoana1.xml"
with open(file, "w", encoding="utf-8-sig") as f:
    f.write(xml_string)
    f.close()